export const OLD_DATE_CONFIRMATION_OPEN = 'OLD_DATE_CONFIRMATION_OPEN';
export type OLD_DATE_CONFIRMATION_OPEN = typeof OLD_DATE_CONFIRMATION_OPEN;

export const OLD_DATE_CONFIRMATION_ACCEPTED = 'OLD_DATE_CONFIRMATION_ACCEPTED';
export type OLD_DATE_CONFIRMATION_ACCEPTED = typeof OLD_DATE_CONFIRMATION_ACCEPTED;

export const OLD_DATE_CONFIRMATION_REJECTED = 'OLD_DATE_CONFIRMATION_REJECTED';
export type OLD_DATE_CONFIRMATION_REJECTED = typeof OLD_DATE_CONFIRMATION_REJECTED;