export const GET_TABLE_DATA_SUCCESS = 'GET_TABLE_DATA_SUCCESS';
export type GET_TABLE_DATA_SUCCESS = typeof GET_TABLE_DATA_SUCCESS;

export const SET__INTERNAL_TABLE_DATA = 'SET__INTERNAL_TABLE_DATA';
export type SET__INTERNAL_TABLE_DATA = typeof SET__INTERNAL_TABLE_DATA;

export const TABLE_REFRESH = 'TABLE_REFRESH';
export type TABLE_REFRESH = typeof TABLE_REFRESH;

export const TABLE_RESET = 'TABLE_RESET';
export type TABLE_RESET = typeof TABLE_RESET;