
module.exports = {
    VUE_APP_BASE_URL: '/',
    VUE_APP_CLIENT_ID: ' eyJpdiI6Ik4wQVZsZWU3MzREVXNzNnZSSGRGdFE9PSIsInZhbHVlIjoiQTVjK2Mza0ZrclA5R3pnd1BNVEpSUT09IiwibWFjIjoiODY5ZTBmOTBmOTlkMzZhZTZkZDBmZjBiYzEwZDhjZDAwOGUwMWYyYTc0YThkZWRkZGI2ZGU4MzM3ZjFhNzc1ZiJ9',
    VUE_APP_DOMAIN_PREFIX:'/',
    VUE_APP_ENTRY: 'src/entry/auth.js',
    VUE_APP_OUTPUT_DIR: 'dist/auth',
    VUE_APP_PORT: 4001
}