<?php

use Illuminate\Database\Seeder;
use App\Models\Institute;
use App\Models\InstituteCategory;


class InstituteFinalTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $institute_categories = ['Hospitals','Polyclinics','Private Clinics','Dental Clinics','Dialysis Centres','Homes','Others'];
        foreach($institute_categories as $key => $institute_category) {

            $response = InstituteCategory::firstOrCreate(
                   ['name' => $institute_category ],
                   ['category_image_id' => null ]);  
            
            if($institute_category == 'Hospitals')   {
		        $institutes = ['Alexandra Hospital','Admiralty Medical Centre','Changi General Hospital','Institute of Mental Health','Jurong Medical Centre','Khoo Teck Puat Hospital','KK Womens And Childrens Hospital ','National Heart Centre of Singapore','Ng Teng Fong General Hospital ','Tan Tock Seng Hospital ','National Cancer Centre','National University Hospital','Singapore General Hospital ','Sengkang General Hospital','Ang Mo Kio - Thye Hua Kwan Hospital Ltd Bright Vision Hospital','Jurong Community Hospital','Ren Ci Community Hospital ','St Andrews Community Hospital St Lukes Hospital (Community) ','Yishun Community Hospital ','Concord International Hospital','Farrer Park Hospital','Gleneagles Hospital','John Hopkins Singapore International Medical Centre Pte Ltd  ','Mt Alvernia Hospital','Mountt Elizabeth Hospital','Mount Elizabeth Novena Hospital','Raffles Hospital Pte Ltd ','Thomson Medical Centre ','Parkway East Hospital','WestPoint Hospital Pte Ltd '];

		        foreach($institutes as  $key => $institute) {

		            $category = InstituteCategory::inRandomOrder()->first();

		            Institute::firstOrCreate([
		            	'name' => $institute,
		            	'institute_category_id' => $response->id,
		            	'registration_no' => rand(111111,999999).$key
		            ]);

		            if($institute == 'MediRad Radiologic Clinic' OR $institute == 'NHG Diagnostics - Xray Laboratory')

		            {
		            	$branches = ['(Breast Imaging Centre – Orchard Road)',
                                                    '(Camden Medical Centre)',
													'(Jurong Gateway Road)',
													'(Mt Elizabeth)',
													'(Napier Road)',
													'(Novena Medical Centre)',
													'Pioneer Polyclinic',
													'(The Arcade Collyer Quay)','Toa Payoh Polyclinic',
													'Woodlands Polyclinic',
													'Ang Mo Kio - Thye Hua Kwan Hospital Ltd ',
													'Ang Mo Kio Polyclinic',
													'Choa Chu Kang Polyclinic',
													'Clementi Polyclinic',
													'Hougang Polyclinic',
													'Jurong Polyclinic',
													'Pioneer Polyclinic',
													'Bukit Batok Polyclinic',
													'Queenstown Polyclinic',
													'Geylang Polyclinic',
													'Xray Bus - 1',
													'Xray Bus - 2',
													'MammoBus - 1',
													'MammoBus - 2',
													'BMD Bus',
													'NTU',
													'NUS' 
                                                ];
					    foreach($branches as  $key => $branch) {	
					      $category = Institute::inRandomOrder()->first();

                           
		                    branch::firstOrCreate([
		            	     'name' => $branch,
		            	     'branch_code' => $response->id,
		            	     'address' => null,
		            	     'institute_id' => $category ? $category->id : null,
		
		                   ]);
                        }
		            }
		        }
            	
            } 

            if($institute_category == 'Polyclinics') {
 
             $institutes =["A Clinic For Women",
                    "A Company For Women",
                    "A L Lim Clinic For Women Pte Ltd",
                    "Abraham’s Ear, Nose & Throat Surgery Pte Ltd ",
                    "Access Medical (Bedok South)",
                    "Advance Surgical Group",
                    "Advanced Centre For Reproductive Medicine Pte. Ltd. ",
                    "Aesthetic Medic ",
                    "Antenatal Diagnostic Centre And Well Women Clinic",
					"Al Partners Aesthetic Plastic Reconstructive Surgery ",
					"Alex Ooi & Associates Obgyn Consultants",
					"Allergy, Arthritis & Rheumatism Clinic",	
					"Alleve Pain Management Centre ",
					"Allure Plastic Surgery",
					"Amandela Ent Head & Neck Centre",
					"Ambulatory Surgicare (Asc)",
					"Andrea’s Digestive, Colon, Liver And Gallbladder Clinic Pte Ltd",
					"Apex Heart Clinic",
					"Apple Ear Nose Throat Sinus And Snoring Centre",
					"Apple Eye Centre",
					"Arthur Tseng Women’s Health Services Pte Ltd",
					"Aptus Surgery Centre",
					"Asia Healthpartners Pte Ltd",
					"Asia Retina Eye Surgery Centre",
					"Asia Sleep Centre",
					"Asiamedic Eye Centre",
					"Asian American Liver Centre",
					"Atlas Eye Specialist Centre",
					"Azataca Plastic Surgery",
					"B K Poh Urology",
					"Balestier Clinic And Health Screening Centre",
					"Beacon Ear Nose Throat Snoring Centre",
					"Beh’s Clinic For Women Pte Ltd",
					"Bertha Woon General And Breast Surgery",
					"BJIOS Orthopaedics",
					"Breast Care And Surgery Centre",
					"BT Goh Family Clinic & Surgery",
					"Bukit Panjang Family Clinic",
					"C F Koh Women’s Clinic And Gynae-Oncology Surgery",
					"C H Koh Clinic For Women",
					"Cape Plastic Surgery Pte Ltd",
					"Capstone Colorectal Surgery Centre",
					"Care Sinus Snoring ENT Centre",
					"Centre For Assisted Reproduction Pte Ltd",
					"Centre For Cosmetic Rejuvenation & Surgery",
					"Centre For Ear Nose Throat Allergy & Sleep",
					"Centre For Eye Surgery",
					"Centre For Hand and Reconstructive Microsurgery (Gleneagles) Pte Ltd ",
					"Centre For Orthopaedics And Hip And Knee Surgery",
					"Centre For Spine And Orthopaedic Surgery",
					"Centre For Sports And Shoulder And Elbow Surgery",
					"Centre For Urology, Robotic & Minimally Invasive Surgery",
					"Centre for Screening & Surgery",
					"Changi Medical Centre",
					"Charles Tan Surgery ",
					"Chee Ear Nose Throat Surgery",
					"Cheng Clinic For Women Pte Ltd",
					"Cheng SC Vein and Endovascular Clinic",
					"Chia Kh Vein Vascular & General Surgery Centre",
					"Children & Adult Skin Hair Laser Clinic",
					"Citizen Family Clinic and Surgery 3",
					"CK Ng Urology & Minimally Invasive Surgery",
					"C K Yong Surgery & Breast Clinic",
					"Clearvision Eye Clinic And Lasik Centre",
					"Clifford Family Clinic",
					"Comfort Clinic & Surgery",
					"Cynthia Kew Clinic for Women & Laparoscopic Surgery",
					"Dental Ear Nose Throat & Snoring Centre Pte Ltd",
					"Dental Focus Junction 10 Clinic",
					"Dentalplus Oral Surgery and Aesthetics",
					"Digestive & Liver Surgery",
					"Dr Alicia Eye Specialist",
					"Dr Angeline Ang & Associates",
					"Dr Goh Eye Neuro-Ophthalmic & Low Vision Specialist",
					"Dr Priya Sen Skin And Laser Centre",
					"Dr JJ Chee Obstetrics & Gynaecology",
					"Drs Chua & Partners (Alexandra Village)",
					"Drs Chua & Partners Pte Ltd",
					"Drs Lim & Chan Clinic",
					"Drs Tang & Associates",
					"Dr Natasha Lim Eye Centre (Mount Elizabeth Novena Specialist Centre) ",
					"Dr Natasha Lim Eye Centre (Royal Square @ Novena)",
					"Dr Ong Theng Kiat Clinic & Surgery For Women",
					"Dream Plastic Surgery",
					"ENT & Sinus Centre",
					"ENT Surgeons Medical Centre",
					"Eastern Hougang",
					"Ear Nose Throat, Head & Neck Surgery",
					"Ear Nose & Throat Partners Pte Ltd",
					"Ear Nose Throat & Snoring Centre",
					"Eden Family Clinic",
					"E Medical Clinic & Surgery (Toa Payoh)",
					"Endoscopy, Veins & Piles Centre",
					"Esther Chuwa Breastcare Practice",
					"Etern Medical Clinic & Surgery",
					"Excellence Healthcare Pte Ltd",
					"Eye & Retina Surgeons",
					"Eye Max Centre ",
					"Fajar Family Clinic & Surgery",
					"Focal Eye Centre",
					"Frontier Specialist Centre",
					"Fullerton Healthcare @ Gethin-Jones",
					"G Chee Ear Nose Throat Sinus & Dizziness Centre ",
					"Gastrointestinal Endoscopy & Liver Centre",
					"Gerald Tan Urology + Robotics",
					"Gerrard Teoh Hematology & Medical Clinic",
					"Gh Chee Ear Nose Throat & Dizziness Centre",
					"Gong Surgery Pte Ltd",
					"Gs Hong Surgical Care",
					"Gynae Health Clinic For Women Pte Ltd",
					"Gynecology Consultants Clinic & Surgery",
					"Haig Specialist O & G Clinic",
					"Hand Wrist & Microsurgical Centre Pte Ltd",
					"HC Orthopaedic Surgery",
					"Heah Colorectal Endoscopy & Piles Centre",
					"Heah Endoscopy & Piles Centre",
					"Health & Fertility Centre For Women",
					"Healthmatters - The Family Practice",
					"Healthlink Family Clinic & Surgery",
					"Healthpath Medical Clinic and Surgery",
					"Healthwerkz Medical Centre (CCK) Pte Ltd",
					"Hii Women’s Clinic",
					"HK Family Clinic & Surgery Pte Ltd",
					"Hn Tay Ent| Head & Neck | Thyroid | Sleep Robotic Surgery ",
					"Ho Kok Sun Colorectal Pte Ltd",
					"Huang Ear Nose Throat Surgery Pte Ltd",
					"Idoc Clinic",
					"Inliven - Center For Osteoarthritis Solutions",
					"Intercept Healthcare Pte Ltd",
					"International Eye Cataract Retina Centre",
					"International Eye Clinic",
					"International Specialist Eye Centre",
					"Irene Chua Clinic For Women",
					"Island Sports Medicine And Surgery",
					"JJ Chua Rejuvenative Cosmetic & Laser Surgery",
					"James Lee Women’s Clinic & Pelvic Floor Surgery",
					"James Tan Centre For Urology And Robotic Surgery",
					"Jerry Tan Eye Surgery Pte Ltd",
					"Jireh Heart Centre",
					"Jude Lee Gastrointestinal & Laparoscopic Surgery ",
					"Julian Lee Ear Nose Throat Specialist",
					"Jurong Medical Centre",
					"K C Chee Surgery",
					"K C Ching Clinic & Surgery For Women",
					"K C Ching Clinic & Surgery For Women Pte Ltd ",
					"K C Yeo Clinic And Surgery For Women Pte Ltd ",
					"K K Ho Clinic For Women",
					"K K Chew Ear, Nose & Throat Surgery",
					"K M Heng Women’s Clinic Pte Ltd",
					"K O Chan Ear Nose Throat Sinus & Sleep",
					"K W Lee Clinic & Surgery For Women",
					"Kensington Family Clinic",
					"KidneyCare Centre",
					"Koh Clinic & Surgery",
					"Kusuma Lee Clinic & Surgery For Women Pte Ltd",
					"L20 Day Surgery Centre Pte. Ltd.",
					"Lang Eye Centre",
					"Lai Endoscopy & Colorectal Surgery",
					"LC Lee Urogynae Centre",
					"Lien Clinic For Women",
					"Lim Clinic",
					"Lim Clinic & Surgery For Women",
					"Lim Ear, Nose & Throat Surgery",
					"Lim Ing Ruen Ent Clinic",
					"Lim Jit Fong Colorectal Centre",
					"Livewell Medical Family Clinic",
					"Luke Tan Ear Nose Throat & Thyroid Surgery",
					"Luke Tan ENT-Head & Neck Cancer and Thyroid Surgery Centre",
					"Lynne Lim Ear Nose Throat and Hearing Centre (Child & Adult)",
					"Marsiling Clinic & Surgery",
					"Md Specialist Healthcare Pte Ltd",
					"Me Novena Specialist Group",
					"Medifast Medical Centre",
					"Mendis Aesthetics & Surgery",
					"ML've URoCare Center",
					"My ENT Specialist (Mount Elizabeth Novena Specialist Centre)",
					"My ENT Specialist (Farrer Park Station)",
					"Myhealth Medical Centre",
					"My Eye Specialist & Retina Surgeon",
					"National Skin Centre",
					"Neuglow The Aesthetics Doctors (OUB Centre)",
					"Neuglow The Aesthetics Doctors (Novena Square 2)",
					"Neuglow The Aesthetics Doctors (Chinatown Point)",
					"Nobel Colorectal & General Surgery",
					"Nobel Ent & Head And Neck Surgery",
					"Nobel Ent, Head, Neck And Thyroid Surgery Centre",
					"Nobel Eye Clinic",
					"Nobel Eye & Vision Centre",
					"Nobel Heart Centre",
					"Nobel Psychological Wellness Clinic",
					"Nobel Surgery Centre ",
					"Northern Hope Medical Specialist",
					"Novena Bladeless Cataract Surgery & Eye Specialist Centre",
					"Novena Cancer Centre",
					"Novena Colorectal Centre",
					"Novena Ent – Head & Neck Surgery Specialist Centre",
					"Novena Surgery Pte Ltd",
					"Nuffield Medical Siglap",
					"Nyam Endoscopy Centre 6",
					"One Surgical Clinic & Surgery",
					"Orchard Surgery Center",
					"Othopaedic & Arthritis Centre",
					"Orthopaedic & Hand MRI (OHM) Novena Pte Ltd",
					"P S Lui Clinic & Surgery For Women",
					"Pacific Endoscopic & Day Surgery Centre",
					"Pacific Healthcare Imaging",
					"Pacific Healthcare Specialist Centre",
					"Pacific Neurosurgery A Centre For Pain Management & Neurosurgery ",
					"Pacific Specialist Centre",
					"Pacific Surgical And Endoscopy Centre",
					"Pacific Surgical Consultants",
					"Pacific Vein And Endovascular Centre",
					"Pacific Women's Clinic and Laparoscopic Surgery Centre",
					"Panasia Surgery Pte Ltd (Mt Elizabeth Medical Centre)",
					"Panasia Surgery Pte Ltd (Parkway East)",
					"Parklane Medical Centre",
					"Parkway East Diabetes, Endocrine and Endovascular Clinic",
					"Parkway Clinic & Surgery Drs Khoo & Partners",
					"Parkwayhealth Day Surgery And Medical Centre",
					"Parkway Eye Centre @ Mount Elizabeth",
					"Parkway Women & Fertility Clinic",
					"Phoenix Medical Group (Paya Lebar)",
					"Pk Women’s Specialist Clinic",
					"Plastic Surgery By S J Lee",
					"Png Urology",
					"Premium Lasik Surgery Clinic",
					"Prenatal Diagnostic Centre",
					"Prime Medical Group Pte Ltd",
					"Prive Clinic",
					"Pacific Heart Centre",
					"Phoenix Dental Surgery",
					"Prohealth Medical Group @Punggol Spectra Pte. Ltd.",
					"Providence Orthopaedics",
					"Punggol Ripples Family Clinic",
					"Raffles Place Specialist Medical Centre",
					"Ravenna Urology Clinic",
					"RMG ED Collaboration",
					"Roland Chieng Fertility And Women Care",
					"S C Low Breast Centre Pte Ltd",
					"SBCC Baby & Child Clinic (Bishan)",
					"SBCC Baby & Child Clinic (Riverdale)",
					"SBCC Baby & Child Clinic (Tiong Bahru)",
					"SBCC Women's Clinic (Clementi)",
					"Shalom Clinic & Surgery ",
					"Shifa Jurong Clinic",
					"Shinagawa Eye Centre Shinagawa Lasik Centre",
					"Sidek Clinic For Women Pte Ltd Sincere Ivf Center ",
					"Sincere Medical Specialist Center For Women Singapore Aeromedical Centre",
					"Singapore International Eye Cataract Retina Centre ",
					"Singapore National Eye Centre",
					"Singapore Sports And Orthopeadic Clinic Pte Ltd ",
					"Singapore Women’s Clinic (Clementi)",
					"Singapore Knee, Sports and Orthopaedic Clinic",
					"S M Chua Clinic & Surgery For Women ",
					"SM Haneefa Clinic SMG ENT Centre Ear Nose Throat Face Neck ",
					"SMG Specialist Centre",
					"SMG Vision Centre",
					"Smg Orthopaedic Group ",
					"Snec Eye Associates",
					"SOC Hong Clinic for Women",
					"SOG- Beh Clinic for Women",
					"SOG - Choo Wan Ling Clinic For Women",
					"SOG - Cindy Pang Clinic for Women & GynaeOncology",
					"SOG- Heng Clinic for Women",
					"SOG - Radhika Breast & General Surgicare",
					"SOG Clinic for Women",
					"SOG - SK Lim Breast & General Surgicare",
					"SOG - Natalie Chua Clinic For Women",
					"Specialist Skin Clinic (S) Pte Ltd",
					"Specialist Women's Clinic",
					"Specialist Women’s Medical Centre",
					"Spring Hope Orthopaedic Spine Surgery",
					"Starcap Medical Group Pte Ltd",
					"Star Health Family Clinic",
					"Sunnyvale Clinic & Surgery",
					"Supersight Lasik Pte Ltd",
					"Sweng Plastic Aesthetic and Reconstructive Surgery Clinic",
					"SW1 Plastic Surgery",
					"Symmetry Dentofacial Aesthetics",
					"Tampines Endoscopy & Surgery Centre",
					"Tampines Gp Ent Urology & Surgery Centre",
					"Tan & Koh Clinic & Surgery",
					"Tan Clinic & Surgery",
					"Tan-Teoh Clinic & Surgery",
					"Tayka Medical",
					"Tcs At Central Clinic",
					"Temasek Clinic And Surgery",
					"The Breast Surgery Centre",
					"The Cancer Centre",
					"The Choolani Clinic",
					"The Dermatology Practice Skin. Hair. Allergy. Laser(Mount Elizabeth Novena Specialist Clinic)",
					"The Dermatology Practice Skin.Hair.Allergy.Laser@Gleneagles",
					"The Digestive & Liver Specialist Centre",
					"The Ear Nose Throat – Head & Neck Centre",
					"The Endoscopy & Piles Centre (Hougang) ",
					"The ENT Clinic",
					"The ENT Clinic Pte Ltd",
					"The ENT Practice",
					"The ENT Specialist Centre",
					"The ENT, Voice & Snoring Clinic",
					"The EyeClinic by Dr Cheryl Lee",
					"The Eye Surgery Partners",
					"The Eye & Aesthetics Clinic",
					"The Eye & Cornea Transplant Centre",
					"The Family Medical Centre (Yishun)",
					"The GP Endoscopy & Piles Centre (Dleedon)",
					"The Harley Street Heart & Cancer Centre 8",
					"The Harley Street Clinic Heart And Cancer Centre",
					"The Head And Neck Surgery Centre",
					"The Heart and Vascular Centre",
					"The Kids Clinic",
					"The Lady Gynaecologist Obstetrician's Clinic Pte Ltd",
					"The Lasik Surgery Clinic",
					"The Lung Specialist Centre",
					"The Medical And Aesthetic Clinic Pte Ltd",
					"The New Teban Clinic",
					"The O&G Care Clinic",
					"The O&G Specialist Clinic",
					"The Obgyn Centre",
					"The Obstetrics And Gynaecology Centre (Paragon)",
					"The Obstetrics And Gynaecology Centre (Parkway East Medical Centre) ",
					"The Radiant Eye Centre",
					"The Rafflesian Clinic & Surgery",
					"The Rhinoplasty Clinic ENT Facial Plastics",
					"The Skin Specialist",
					"The Skin Specialists & Laser Clinic",
					"The Tow Yung Clinic",
					"The Vascular & General Surgery Centre",
					"The Vein Clinic & Surgery Pte Ltd",
					"The Women’s Clinic & Surgery",
					"The Women’s Specialist Centre (Aljunied)",
					"The Women’s Specialist Centre (Gleneagles)",
					"The Women’s Specialist Centre (Hougang)",
					"Thomson Fertility Centre",
					"Thomson Paediatric Centre (Thomson Medical Centre)",
					"Thomson Paediatric Centre (Hillion Mall)",
					"Thomson Specialist Skin Centre",
					"Thomson Women's Clinic (Serangoon) Pte. Ltd",
					"Thomson Women's Clinic (at Toa Payoh)",
					"Twin City Perio-Endo Clinic Pte Ltd",
					"TLC Gynaecology Practice Clinic & Surgery for Women",
					"TLC Lifestyle Practice",
					"Toh Khai Lee Urology Clinic",
					"Total Eyecare Centre",
					"Universal Medical Clinic",
					"Viva Medical Clinic",
					"Vivien @ Robinson.Practice",
					"WC Ong Plastic Reconstructive Surgery",
					"W Eye Clinic",
					"W S Law Medical Centre ",
					"Wee Breast & General Surgery Pte Ltd Wendy Women’s Clinic",
					"Women’s Clinic Of Singapore",
					"Wisma Geylang Serai Clinic & Surgery Y Y Tan’s Clinic For Women Pte Ltd ",
					"Yap Family Clinic ",
					"YH Goh Ear Nose Throat, Head & Neck Surgery Zenith Medical Clinic",
					"Access Medical (Bukit Batok)",
					"Access Medical (Circuit Road)",
					"Access Medical (East Coast)",
					"Access Medical (Jurong West)",
					"Access Medical (Kim Keat)",
					"Access Medical (Marine Terrace)",
					"Access Medical (Redhill Close)",
					"Access Medical (Tampines 730)",
					"Access Medical (Toa Payoh)",
					"Access Medical (Whampoa)",
					"Access Medical (Teck Ghee)",
					"Ascent Ear Nose Throat Sg Alvernia",
					"Ascent Ear Nose Throat Sg East",
					"Ascent Ear Nose Throat Specialist Group",
					"Astra Centre for Women & Fertility Pte. Ltd.",
					"Astra Laparoscopic & Robotic Centre For Women and Fertility",
					"Astra Women's Specialist Clinic",
					"Astra Women's Specialists Centre (Bishan)",
					"Astra Women's Specialists Centre (Toa Payoh Central)",
					"Dermatology Associates (Connexion)",
					"Dermatology Associates (Gleneagles)",
					"Dermatology Associates (Paragon)",
					"Dermatology & Surgery Clinic (Orchard)",
					"Dermatology & Surgery Clinic (Shenton)",
					"Eagle Eye Centre",
					"Eagle Eye Centre Pte Ltd (Eec)",
					"Eagle Eye Centre (East Shore)",
					"Eagle Eye Centre (Mt Elizabeth Novena Specialist Centre)",
					"Eagle Eye Centre (Gleneagles Medical Centre)",
					"Eagle Eye Centre (Mt Elizabeth Medical Centre)",
					"Flinders Practice Pte Ltd (Anson Road)",
					"Flinders Practice Pte Ltd (Middle Road)",
					"Hand Surgery Associates",
					"Hand Surgery Associates (Alvernia)",
					"Hand Surgery Associates (Gleneagles) Private Limited ",
					"Hand Surgery Associates (Parkway East)",
					"Hand Surgery Associates (Farrer Park) Pte. Ltd.",
					"HC Endoscopy & Piles Centre (GM)",
					"HC Endoscopy & Piles Centre (Hillford)",
					"Island Orthopaedic Consultants",
					"Island Orthopaedic Consultants Pte Ltd (Mt A)",
					"Island Orthopaedic Consultants Pte Ltd (Mt E)",
					"Asian American Blood & Marrow Transplant Centre C K Yong Surgery & Breast Clinic",
					"Colorectal Clinic Associates ",
					"Dr D.Y.H Poon & Associates Medical Oncology Clinic Pte. Ltd. ",
					"Elizabeth Au Oncology",
					"Gynaecology & Oncology Specialists",
					"Gynecology & Associates",
					"Gynecology Consultants Clinic & Surgery",
					"GS Hong Surgical Care",
					"Haematology And Cancer Centre",
					"Haematology Oncology Centre",
					"H L Kong Medical Oncology Centre (Novena Medical Centre) ",
					"H L Kong Medical Oncology Centre (Paragon, Orchard Road) ",
					"International Cancer Specialist",
					"Joanna Lin’s Medical And Cancer Clinic Pte Ltd",
					"K S Khoo Medical Oncology",
					"Lisa Wong Women & Gynae Oncology Centre ",
					"Lucence Diagnostics Medical Centre Medical & Haematology Clinic",
					"Lucence Diagnostics Medical Centre Medical & Haematology Clinic",
					"Medical Oncology Centre",
					"Medical Oncology Specialist Clinic Pte Ltd Mow Blood & Cancer Clinic Pte Ltd ",
					"MRI Center for the Extremities (MCE) Pte. Ltd.",
					"ML've Healthcare (Novena)",
					"Novena Cancer Centre",
					"OncoCare Cancer Centre – Gleneagles Medical Centre",
					"OncoCare Cancer Centre - Gleneagles Hospital",
					"OncoCare Cancer Centre - Mt Alvernia Medical Centre",
					"OncoCare Cancer Centre – Mount Elizabeth Medical Centre ",
					"OncoCare Cancer Centre – Mount Elizabeth Novena Specialist Centre ",
					"OncoCare Women’s Cancer Clinic ",
					"P T Ang Medical Oncology Clinic",
					"Pacific Cancer Centre",
					"Parkway Cancer Centre (Gleneagles Hospital Annexe Block) ",
					"Parkway Cancer Centre (Gleneagles Hospital Level 1)",
					"Parkway Cancer Centre (Gleneagles Hospital Level 2)",
					"Parkway Cancer Centre (Mount Elizabeth Medical Centre)",
					"Parkway Cancer Centre (Mount Elizabeth Hospital)",
					"Parkway Cancer Centre (Mount Elizabeth Novena Specialist Centre) ",
					"Parkway Cancer Centre (Parkway East Hospital)",
					"Pritam’s Clinic & Surgery For Women Pte Ltd",
					"Seow-Choen Colorectal Centre Pte Ltd",
					"Singapore Medical Specialists Centre",
					"Singapore Oncology Consultants@Alvernia",
					"The Blood Specialists",
					"The Cancer Centre (Paragon)",
					"The Cancer Centre (Mount Elizabeth Novena Specialist Centre)",
					"The Oncology Centre",
					"Thomson Women Cancer Centre",
					"Tucker Medical",
					"Wee Breast & General Surgery Pte Ltd",
					"Y O Tan Medical Oncology",
					"Yim Gastroenterology Liver And Endoscopy Centre ",
					"Cairnhill X-Ray Clinic & Laboratory",
					"Drs. Lim, Hoe & Wong Radiology Pte Ltd (Jurong Point)",
					"Drs. Lim, Hoe & Wong Radiology Pte Ltd (Orchard Building)",
					"Radoc Imaging Radiology Centre",
					"Radlink Diagnostic Imaging (S) Pte. Ltd.",
					"Radlink Pet And Cardiac Imaging Centre Pte Ltd",
					"The Orchard Imaging Centre Pte Ltd",
					"Advanced Medicine Imaging",
					"Drs Jiten & Caroline Medical Centre + X-Ray",
					"Farrer Park Imaging",
					"Pacific Healthcare Imaging",
					"Prestige Radiology & Diagnostic Centre Pte Ltd",
					"MediRad Radiologic Clinic ",
					"NHG Diagnostics - Xray Laboratory",
					];

			   foreach($institutes as  $key => $institute) {

		            $category = InstituteCategory::inRandomOrder()->first();

		            Institute::firstOrCreate([
		            	'name' => $institute,
		            	'institute_category_id' => $response->id,
		            	'registration_no' => rand(111111,999999).$key
		            ]);
		        }
            }

            if($institute_category == 'Dialysis Centres')   {

             $institutes = ['Advance Dialysis Services Pte.Ltd.Advance Renal  Therapy',
						'Advance Renal Care (Kovan) Aegis Dialysis Centre Pte Ltd', 
						'ARC Kidney Dialysis Centre (Clementi) ARC Kidney Dialysis Centre (Kembangan)', 
						'ARCA(Farrer Park) Dialysis Pte Ltd',
						'Asia Kidney Dialysis Centre (Bedok) Pte Ltd',
						'Asia Kidney Dialysis Centre (Jurong)',
						'Asia Kidney Dialysis Centre (Teck Whye)',
						'Asia Kidney Dialysis Centre (Tampines)',
						'Asia Kidney Dialysis Centre (Toa Payoh) 24',
						'Asia Renal Care Mt Elizabeth Pte Ltd',
						'Asia Renal Care (Katong) Pte Ltd',
						'Asian Centre For Liver Diseases & Transplanation Pte Ltd',
						'Ang Mo Kio Thye Hua Kwan Hospital Dialysis Centre',
						'B. Braun Avitum Dialysis Centre',
						'B.Braun Dialysis Centre (Ang Mo Kio)Centre For Kidney Diseases Pte Ltd Dialysis Centre – Youngberg Pte Ltd',
						'Dialysis Youngberg Pte Ltd (Serangoon)',
						'Dialysis Youngberg Pte Ltd (Kovan)',
						'Econ Advance Renal Care (Yung Kuang)',
						'Econ Advance Renal Care (Bedok)',
						'Fhc Dialysis Centre Pte Ltd',
						'Fresenius Medical Care Bukit Merah Central Dialysis Clinic',
						'Fresenius Medical Care Gleneagles Dialysis Clinic',
						'Fresenius Medical Care Khatib Dialysis Clinic',
						'Fresenius Medical Care Teck Whye Dialysis Clinic',
						'Fresenius Med Care Bukit Merah',
						'Fresenius Me Care Jr Boon Lay',
						'Fresenius Med Care Jurong East',
						'Fresenius Medical Care Jurong East Central Dialysis Clinic',
						'Fresenius Medical Care – Kovan',
						'Fresenius Med Care Lucky Plaza',
						'Fresenius Medical Care - Marsiling Dialysis Clinic',
						'Fresenius Medical Care – Serangoon',
						'Fresenius Medical Care - Upper Serangoon',
						'Fresenius Medical Care Tampines',
						'Fresenius Medical Care Toa Payoh',
						'Fresenius Medical Care – Whampoa',
						'Fresenius Medical Care Yishun Ring Dialysis',
						'Fresenius Medical Care Ang mo kio Dialysis clinic',
						'Gleneagles Dialysis International Pte Ltd',
						'Grace Lee Renal & Medical Clinic',
						'Immanuel Dialysis Centre Pte Ltd',
						'Immanuel Dialysis Centre (AMK) Pte Ltd',
						'Immanuel Dialysis Centre (Mayflower) Pte Ltd',
						'Immanuel Dialysis Centre (Woodlands) Pte Ltd',
						'Immanuel Dialysis Centre (Yishun) Pte Ltd',
						'Immanuel Dialysis Centre Pte Ltd (at Mount Alvernia Medical Centre) Kidney Dialysis Centre',
						'Kidney Dialysis Centre (Bedok) Pte Ltd',
						'Kidney Dialysis Foundation Ltd Pte Ltd',
						'Kidney Medical Centre',
						'Kidney Life Centre',
						'Kidneycare Dialysis Centre @ Pasir Ris',
						'Kidneycare Dialysis Centre @ Yishun',
						'Kidneycare Dialysis Cente @ West Coast',
						'Ku Kidney & Medical Centre',
						'MTFA Dialysis Centre',
						'National Kidney Foundation',
						'Nephrocare Singapore Dialysis Centre Nephrocare S&J Dialysis Centre',
						'Pacific Advance Renal Care (Punggol)',
						'Pacific Advance Renal Care (Tampines) Pacific Advance Renal Care (Woodlands) Pacific Advance Renal Care (Fajar)',
						'Pacific Advance Renal Care (Choa Chu Kang)', 
						'Pacific Advance Renal Care (Sengkang)',
						'Peoples Dialysis Centre', 
						'Renal & Dialysis (S) Pte Ltd',
						'Renal Health Pte Ltd',
						'Renal Life (W) Dialysis Centre Pte Ltd',
						'Renal Life Dialysis Centre Pte Ltd',
						'Renal Life (Hougang) Dialysis Centre Pte Ltd',
						'Renal life (Pioneer) Dialysis Centre',
						'Renal Medical Services Pte Ltd (Hougang)',
						'RenalTeam Dialysis Centre Ang Mo Kio',
						'RenalTeam Dialysis Centre Bedok',
						'RenalTeam Dialysis Centre Bukit Merah',
						'RenalTeam Dialysis Centre Jurong East',
						'RenalTeam Dialysis Centre Ren Ci Community Hospital',
						'RenalTeam Dialysis Centre Tampines',
						'RenalTeam Dialysis Centre Woodlands',
						'Renalteam Dialysis Centre Woodlands Peak',
						'RenalTeam Dialysis Centre Yishun',
						'Sh Tan Kidney And Medical Clinic (Mount Elizabeth Medical Centre)',
						'Sh Tan Kidney And Medical Clinic Pte Ltd (Gleneagles Medical Centre)', 
						'Singapore Childrens Society SGH Peritoneal Dialysis (Pd) Centre', 
						'Stephen Chew Centre For Kidney Disease And Hypertension Pte Ltd', 
						'TAL Dialysis',
						'T G Ng Kidney & Medical Centre',
						'The Kidney Clinic Pte Ltd',
						'The Singapore Clinic For Kidney Dieases' ];

			   foreach($institutes as  $key => $institute) {

		          $category = InstituteCategory::inRandomOrder()->first();

		           Institute::firstOrCreate([
		            	'name' => $institute,
		            	'institute_category_id' => $response->id,
		            	'registration_no' => rand(111111,999999).$key
		            ]);
		        }

            }

           if($institute_category == 'Dental Clinics')   {
             $institutes = ['@ Just Braces Dental Centre',
						'A Dental Clinic @ Clementi Central Pte Ltd',
						'A Dental Clinic @Jurong East Central',
						'A St*R Dental Surgery (Ang Mo Kio)',
						'A St*R Dental Surgery (Ghim Moh Link)',
						'AA Dental Surgery',
						'Aaron Ctp Dental Surgery Pte Ltd',
						'Aaron Dentalcare Pte Ltd',
						'Aaron Dentalcare @ Holland V.',
						'Aaron Seow Dental Surgery',
						'About Braces Dental Surgery',
						'Accent Dental Surgery Pte Ltd',
						'Ace Dental Centre',
						'Ace Family Dentalcare',
						'Advanced Dental Surgery Pte Ltd',
						'Advanced Dental Clinic (Bedok) Pte. Ltd. ',
						'Advanced Dental Clinic (East Coast) Pte. Ltd. ',
						'Advanced Dental Clinic (Jurong West) Pte. Ltd. ',
						'Advanced Dental Clinic (Toa Payoh) Pte. Ltd. ',
						'Advanced Dental Clinic Serangoon Pte Ltd ',
						'Advanced Dental Clinic Sengkang Pte Ltd ',
						'Advanced Dental Clinic Pasir Ris Pte Ltd',
						'Advanced Dental Clinic Whampoa Pte Ltd',
						'Advanced Dental Clinic Bukit Panjang Pte. Ltd ',
						'Advanced Dental Ang Mo Kio Pte. Ltd.',
						'Advent Dental Surgery Pte. Ltd.',
						'Advent Endodontics Inc Pte Ltd',
						'Aesthete Smilestudio',
						'Aesthetic Reconstructive Jaw Surgery Aesthetics Dental Surgery',
						'Aesthetic and Reconstructive Centre Pte. Ltd. ',
						'Aelite Implant & Dental Center Pte Ltd',
						'Alda Dental Surgery (Tampines)',
						'Alda Dental Surgery (Tanglin)',
						'Aljunied Dental Surgery',
						'Allsmiles Dental Care Pte Ltd',
						'Allsmiles Dental Care Plus',
						'Aloha Dental Clinic',
						'Aloha Dental Pte Ltd',
						'Alpha Dental Group',
						'Amical Dental Surgery',
						'Amoy Street Dental',
						'Ang Dental Surgery',
						'Ang Mo Kio 10 Dental',
						'Ann Arbor Dental Surgery Pte Ltd ',
						'Apex Dental Surgery',
						'Apollonia Dental Surgery Ascension Dental Clinic',
						'Ashford Dental Centre',
						'Asia Healthcare Dental Surgeons ',
						'Atlantic Dental Surgery ',
						'Atria-City Dental Group Pte Ltd',
						'Atria-Pan Dental Group',
						'Audrey & Alexander Centre For General Dentistry ',
						'Aura Dental Clinic ',
						'Azure Dental',
						'Balestier Dental Surgery',
						'B9 Dental Centre (Clementi)',
						'B9 Dental Centre (Hdb Hub)',
						'B9 Dental Centre (The Star Vista Exchange Green) ',
						'B9 Dental Centre (Marsiling)',
						'B9 Dental Centre (Tanjong Pagar)',
						'Bernard Tan Dental Surgery Pte Ltd',
						'Bethel Dental Surgery',
						'Bedok Town Dental Surgery',
						'Boon Lay Dental Surgery Pte Ltd',
						'Braces & Aesthetics Dental Clinic Pte Ltd',
						'Braces & Implant Dental Centre',
						'Brickworks Dental Surgery',
						'Bright Smile Dental Surgery',
						'Brilliant Dental Surgery',
						'British Dental Surgery',
						'Broad Smile Dental Pte Ltd',
						'Bukit Batok Dental Surgery',
						'Bukit Timah Dental Clinic Llp',
						'Bukit Timah Nam Seng Dental Surgery',
						'Burlinson Dental Surgery',
						'C & A Dental Studio',
						'C & A Dental Studio @ Parkway Parade',
						'C & A Dental Studio @ UE Square',
						'C & A Dental Studio @ Thomson',
						'Canaan Dental Surgery Pte Ltd',
						'Careway Dental Surgery',
						'Caring Dental',
						'Caring Dental (Sengkang)',
						'Caring Dental (Punggol)',
						'Casa Dental',
						'Casa Dental (AMK)',
						'Casa Dental (Holland)',
						'C C Tang Dental Surgery Pte. Ltd.',
						'Central Clinic & Surgery (Bedok)',
						'Central Clinic & Surgery (Clementi)',
						'Central Clinic & Surgery (Hougang)',
						'Central Clinic & Surgery (Yishun)',
						'Century Dental Care',
						'Chanmee Family Dentalcare Pte Ltd',
						'Charismile Dentisry',
						'Charles Dental Surgery',
						'Chen Dental Surgery',
						'Cheok Dental Surgery',
						'Chew & Chew Dental Surgery Pte Ltd ',
						'Chia & Lee Medical & Dental Clinic',
						' Chin Dental Surgery Pte Ltd',
						'Chng Dental Surgery',
						'Choo Dental Surgery ',
						'Chua Kay Hian Dental Surgery',
						'City Dental Surgery',
						'City Hall Dental Centre',
						'Clementi Dental Centre ',
						'Cluny Court Family Dental Pte. Ltd.',
						'Coast Dental',
						'Covenant Dental Surgery',
						'Cozy Dental Group ',
						'Chris Dental Surgeons',
						'Comfort Dental Surgery',
						'Corporate Dental Clinic (Haig Road) Pte Ltd ',
						'Crescent Dental Clinic',
						'Crown Dental Clinic',
						'Crown Dental Surgery',
						'Crest Family Clinic & Dental Surgery',
						'De Dental Clinic Pte Ltd',
						'De Dental Practice Pte Ltd',
						'De Dental Practice Two Pte. Ltd',
						'De Pacific Dental Group (AMK) Pte Ltd',
						'De Pacific Dental Group (Balestier) Pte Ltd',
						'De Pacific Dental Group (Jurong West) Pte Ltd ',
						'De Pacific Dental Group (Pasir Ris) Pte Ltd ',
						'Delta Dental Pte Ltd',
						'Dennis Tan Dental Surgery Pte Ltd',
						'Dental Care@Fajar Pte Ltd',
						'Dental Designs Clinic Pte Ltd.',
						'Dental Focus Pioneer Clinic',
						'Dental Icon @ Costa',
						'Dental On The Bay',
						'Dental Suites @ Bedok',
						'Dental Surgery Centre',
						'DentalFamily (Pioneer)',
						'DentalPlus Clinic Pte Ltd ',
						'DentalSpecialists@Scotts',
						'DentalTalk UBI',
						'Dental Focus AMK 339 Clinic',
						'Dental Focus AMK 532 Clinic',
						'DentalTown (Bedok Reservoir) Pte Ltd',
						'Dental Essence',
						'Dental Focus BMP Clinic',
						'Dental Focus Capitol Clinic',
						'Dental Focus Eunos Clinic',
						'Dental Focus GSM Clinic',
						'Dental Focus Haig Clinic',
						'Dental Focus Hougang Green Clinic',
						'Dental Focus People’s Park Clinic',
						'Dental Focus Yishun Clinic',
						'Dentaltrendz Pte Ltd',
						'DentalTrendz Clinic',
						'Dental Werks@Farrer',
						'Dental Werks@Sembawang ',
						'Dentalworks Pte Ltd',
						'Dentalworkz Studio',
						'dental @ UNI',
						'Dental Icon',
						'Dentigiene Dental Surgery Pte Ltd ',
						'Dhoby Dental Surgery LLP ',
						'Dover Dental Surgery',
						'DP Dental Pte Ltd',
						'Dr David K L Tay & Associates',
						'Dr H C Leong Dental Surgeon LLP',
						'Dr Jimmy Yap & Partners Dental Surgeons',
						'Dr Lams Dental Surgery',
						'Dr Seah Root Canal + Implant Surgical Clinic',
						'Dr Seow Dental Centre',
						'Dr. Smile Dental Clinic',
						'Drs. Ernest Lam & Partners Dental Surgeons',
						'Drs K.S. Wong & Partners Dental Surgery Pte Ltd',
						'Eastcare Pain Specialist',
						'Eastwood Dentalcare Family Dental Clinic',
						'Eden Dental Surgery',
						'Edwin Ng Teck Hong Dental Surgery',
						'Elias Dental Surgery',
						'Eli Dental Surgery',
						'Elite Dental Group Pte Ltd',
						'Enhance Dental Centre',
						'Epismile Inc Dental Group Pte Ltd',
						'Epismile (Bt Batok) Dental Group Pte. Ltd.',
						'Expat Dental',
						'Excelsior Dental Surgery Pte Ltd',
						'Facial Aesthetics Dental Surgery',
						'Family Dental Surgery',
						'Family Dental Surgery Pte Ltd',
						'Fdc @ Harbourpoint Dental Centre',
						'FDC Dental Bedok Central',
						'First Avenue Dental Surgery',
						'First Impressions Dental Surgery Pte Ltd',
						'Flozz Dental Surgery',
						'Foo & Associates Dental Surgeons',
						'Freia Medical',
						'Friends Dental Surgeons',
						'Fullerton Dental @ NTU',
						'Fusion Dental',
						'G Dental Center',
						'G.Dental @ Clementi',
						'Garden Dental',
						'Gateway Dental Center',
						'Gateway Dental Surgeon',
						'Gentle Dental Centre for Aesthetics and Implantology Pte Ltd ',
						'Gentle Dental Group @Bukit Timah',
						'Gentle Dental Group Pte Ltd',
						'Gentle Dental Group @ Tanjong Katong Pte. Ltd.',
						'Ginza Dental Surgery',
						'Glee! Dental Surgery',
						'Glittz Smile Dental Surgery',
						'Glory Dental Surgery ',
						'Greenlife Dental Clinic (Beach Road)',
						'GreenLife Dental Clinic (Ang Mo Kio)',
						'Greenlife Dental Clinic (New Upper Changi Road) ',
						'Greenlife Dental Clinic (Clementi) ',
						'Greenlife Dental Clinic (at Toa Payoh Central)',
						'Greenlife Dental Clinic (at Yew Tee Square)',
						'GPA Centre for Dentistry',
						'Gpa Dentalcare@Goldhill Pte Ltd',
						'Gpa Studio For Dentistry',
						'Glory Dental Surgery (Roxy Square) Pte. Ltd.',
						'H H Lee & Associates Dental Surgery',
						'Happy Tooth Dental Pte Ltd',
						'Harbourpoint Dental Centre',
						'Harmony Dental Surgery',
						'Heal Dental Clinic',
						'Healthteeth Dental Surgery',
						'Healthway Dental Clinic',
						'Healthway Dental Clinic (Braddel)',
						'Healthway Dental Clinic (Bukit Batok)',
						'Healthway Dental Clinic (Fajar)',
						'Healthway Dental Clinic (Jalan Damai)',
						'Healthway Dental Clinic (Westgate Gateway Drive)',
						'Healthway Dental Clinic  (Yishun)',
						'Healthway Dental Clinic (Holland Drive)',
						'Healthway Dental Clinic (Robinson Square) ',
						'Henry Lee Dental Surgery',
						'Heritage Dental',
						'Ho Dental Surgery',
						'Ho Dental Surgery – Marine Parade',
						'Ho Kee Hai & Partners Dental Implant Maxillofacial Aesthetic Centre',
						'Horizon Dental Surgery',
						'Holland Dental Pte. Ltd.',
						'Holland Village Dental Surgery',
						'Hosanna! Dental Surgery',
						'Hougang Central Dental Surgery',
						'Hougang Dental Centre',
						'Hospital Dental Surgery',
						'Hsuan & Xiaohui OG Clinic',
						'Island Group Dental Surgery',
						'I Care Dental',
						'I Care Dental Pte Ltd',
						'Icon Dental Surgeons',
						'I.Dental @ Northpoint Pte Ltd',
						'I.Dental Invisalign Dedicated Clinic',
						'I.Dental Surgeons',
						'IMC Dental',
						'Implant Dental Centre',
						'Implantdontics Cosmetic And Implant Dentistry',
						'International Dental Centre',
						'International Plaza Dental Surgeons',
						'Irene Chua Dental Surgery',
						'Ismile Dental Clinic',
						'Ismile Studio Pte Ltd',
						'J Dental',
						'J.K. Leong (Dental Centre) Pte Ltd ',
						'Jesselton Dental Centre',
						'Johan Dental Surgery Pte Ltd 14',
						'Joy Dental Centre',
						'Joy Lee Breast and General Surgery',
						'Junction 8 Dental Surgery Pte Ltd',
						'Jurong Dental Surgery',
						'Jurong Point Dental Surgery',
						'K C Tan’s Clinic & Bright Dental Surgery',
						'Kaiser’s Zahnklinik Pte Ltd',
						'Kang Ren Dental Surgery',
						'Katong Dental Surgery',
						'Khoo Dental Surgery',
						'Kids Dental World',
						'Killiney Dental Centre',
						'King’s Dental Surgery (Kovan) Pte Ltd',
						'Ko Djeng Dental Centre',
						'Ko Djeng Dental Centre (Jelita Branch)',
						'Ko Djeng Dental Centre (Tanjong Pagar)',
						'Ko Djeng Gleneagles Pte Ltd (at Lucky Plaza)',
						'Ko Djeng Sakura Dental Clinic',
						'Koh Dental Surgery Pte Ltd – Hong Leong',
						'Koh Dental Surgery Pte Ltd – Jurong East',
						'Koh Dental Surgery Pte Ltd – Newest West Coast ',
						'Kong Dental Surgery (Limbang Shopping Centre) ',
						'Kong Dental Surgery (Teck Whye Lane)',
						'Kong Dental Surgery (Sunshine Place)',
						'Kong Dental Surgery (JURONG GATEWAY) ',
						'L’ving Vine Dental Clinic',
						'Lakeside Dentist',
						'Lam Dental Surgery Pte Ltd',
						'LVDA Dental Centre',
						'Le Mint’s Dental Practice',
						'Le Mints Oral Maxillofacial Surgery (The Adelphi) Le Mints Oral Maxillofacial Surgery',
						'Lee Dentalcare Pte Ltd',
						'Lee & Associates Dentalcare',
						'Lee & Lee (Dental Surgeons) Pte Ltd (Bukit Batok) ',
						'Lee & Lee (Dental Surgeons) Pte Ltd (Tampines) ',
						'Lee & Lee Dental Surgeons Pte Ltd (Collyer Quay) ',
						'Lee & Ong Dental Surgeons',
						'Lee & Ong Dental Surgeons Pte Ltd',
						'Lee Dental Surgery Pte Ltd',
						'Lee Clinic/Lee Dental Surgery',
						'Lee Dental Surgery (Tampines)',
						'Li Dental Centre Pte Ltd',
						'Lim K A Oral & Maxillofacial Surgery',
						'Little India Dentist Pte. Ltd.',
						'Liverpool Dental Care',
						'Logos Dental Surgery',
						'Loh Dental Surgery',
						'Loh Fun Chee & Associates Pte Ltd',
						'London Dental Care Pte Ltd',
						'Loyal Dental Pte Ltd',
						'LQ Dental',
						'LU_Ally Dental Surgery ',
						'Luminous Dental Clinic @ 25A Chai Chee',
						'Luminous Dental Clinic @ Bedok Point Pte Ltd',
						'Luminous Dental Clinic @ Tampines 15',
						'Luminous Dental Clinic @ 821 Tampines',
						'Luminous Dental Clinic @ Tampines Plaza',
						'Luminous Dental Clinic @ 201D Tampines',
						'Luminous Dental Clinic @ Hougang ',
						'Luminous Dental Clinic @ Pasir Ris ',
						'Luminous Dental @ Raffles Place ',
						'Luminous Dental Clinic @ Yishun ',
						'M Dental (Pasir Ris) Pte Ltd',
						'Mandarin Dental Centre (Bt) Pte Ltd',
						'Mandarin Dental Centre (Katong) Pte Ltd',
						'Mandarin Dental Centre Pte Ltd (Bukit Merah Central) ',
						'Madeliene Gunaratnam Dental Surgery',
						'Maritime Dental Surgery Pte Ltd',
						'Medical-Dental Oral And Maxillofacial Surgery',
						'Medical And Dental Centre @ Commonwealth ',
						'Medicare Associates & Dental Surgery',
						'Meiplus Dentalcare (Far East Square)',
						'Meiplus Dentalcare (Tanjong Pagar)',
						'Metro Dental @ Marina',
						'Millennium Dental Care',
						'Mission Dental Surgery',
						'Mount Elizabeth Dental Surgery Pte Ltd',
						'Mouth Dental Surgery',
						'Mt A Dental Centre',
						'MySmile Dental Clinic',
						'My Braces Clinic',
						'My Dentist’s Clinique',
						'My Family Dental Serangoon',
						'N.K. Cheong Dental Clinic',
						'NF DentiSmile',
						'NF DentiSmile @ MarinaSq',
						'Nam Fung Dental Surgery Pte Ltd',
						'Nam Sang Dental Surgery',
						'Marina Bay Dental',
						'National Dental Centre',
						'National Healthcare Group Polyclinics (Ang Mo Kio)',
						'National Healthcare Group Polyclinics (Bukit Batok)',
						'National Healthcare Group Polyclinics (Choa Chu kang)',
						'National Healthcare Group Polyclinics (Clementi)',
						'National Healthcare Group Polyclinics (Hougang)',
						'National Healthcare Group Polyclinics (Jurong)',
						'National Healthcare Group Polyclinics (Toa Payoh)',
						'National Healthcare Group Polyclinics (Woodlands)',
						'National Healthcare Group Polyclinics (Yishun) ',
						'Nanyang Dentist',
						'NEUGen Dental',
						'Neighbourhood Dental Surgery',
						'Neo Smiles Dental Studio (Bedok)',
						'Neo Smiles Dental Studio (Kovan)',
						'Neptune Dental Group',
						'Neptune Dental Group (Chai Chee) ',
						'Neptune Dental Group (Clementi)',
						'Neua Dental',
						'Neuglow Dental',
						'NeuSmile Dental Group (Kovan) Pte Ltd ',
						'New Age Cosmetic Dentists ',
						'New Dental Centre',
						'New Life Dental Surgery 16',
						'Newlife Dental Practice Pte Ltd',
						'Newport Dental',
						'Ng & Lum Dental Surgery',
						'Ngoi Dental Surgery',
						'Noble Dental Surgery',
						'Nour!sh Dental Care & Implants',
						'Novena Dental Aesthetic Practice Pte Ltd Ctr For Aesthetic Dentistry Nuffield Dental @ Kovan',
						'Nuffield Dental Seletar',
						'Nuffield Dental Serangoon Gardens Private Limited',
						'Nuffield Dental Siglap',
						'Nuffied Dental (Simpang Bedok) Pte. Ltd.',
						'Ocean Dental',
						'OKIO Dental Centre',
						'Oliver Dental Surgery Pte Ltd',
						'Oliver Dental Surgery Pte Ltd – Mini Dental Implant Centre',
						'Omni Dental Centre',
						'OneCare Clinic Boon Lay',
						'OneCare Clinic Choa Chu Kang',
						'Onecare Clinic Marine Parade',
						'One Orthodontics Dental Surgery',
						'Oral-Health Dental Surgery',
						'Orange Dental Clinic Pte Ltd',
						'Orange Orthodontics & Dentofacial Orthopaedics',
						'Orchard Dental Surgery',
						'Orchard Scotts Dental: Aesthetics and Implant Center Pte. Ltd. ',
						'Scotts Dental Pte Ltd',
						'Orient Dental Clinic',
						'Orthosmile Dental Practice Llp',
						'Pacific Dental',
						'Pacific Medical & Dental Group',
						'Pan Island Dental Surgery',
						'Pang & Ng Dental Surgery (Bishan) Pte. Ltd.',
						'Pang & Ng Dental Surgery (Hougang) Pte. Ltd.',
						'Paramount Dental Clinic',
						'Paragon Dental Centre',
						'Parkway Dental Practice',
						'Parkway Dental Services',
						'People’s Dental Surgery',
						'Perumal Dental Surgery',
						'Petite Smiles Childrens Dental Clinic',
						'Philip Goh Dental Surgery',
						'Pinnacle Dental',
						'Pinnacle Dental Group (Yishun)',
						'Pinnacle Dental Group Pte Ltd',
						'Planet Dental Centre',
						'Plaza Dental',
						'Polygems (PG) Dental Care Pte. Ltd. ',
						'Polygems Dental Care (Yishun)',
						'Polygems Dental Care (Seletar)',
						'Poon & Phay Dental Surgeons Pte Ltd',
						'Popular Dental (Woodlands)',
						'Popular Dental (Choa Chu Kang)',
						'Popular Dental (Serangoon Central)',
						'Premier Dental Clinic',
						'Premier Dental Care',
						'Princeton Dental Surgery',
						'Prime Dental Surgeons Pte Ltd',
						'Primecare Dental Clinic',
						'Pristine Dental Works Profile Dental Surgery Pte Ltd ',
						'Pure Dental',
						'Pure NZ Dental',
						'Q & M Dental Centre (Bugis)',
						'Q & M Dental Centre (Bugis Village)',
						'Q & M Dental Centre (Bukit Batok Central)',
						'Q & M Dental Centre (Novena)',
						'Q & M Dental Centre (Orchard)',
						'Q & M Dental Centre (Raffles Place)',
						'Q & M Dental Centre (Toh Yi)',
						'Q & M Dental Centre (City Square Mall)',
						'Q & M Dental Centre (Sun Plaza)',
						'Q & M Dental Centre (Yew Tee)',
						'Q & M Dental Clinic',
						'Q & M Dental Clinic (Clementi)',
						'Q & M Dental Clinic (Serangoon Central)',
						'Q & M Dental Clinic (Tiong Bahru)',
						'Q & M Dental Clinic (Toa Payoh Central)',
						'Q & M Dental Clinic (Toa Payoh)',
						'Q & M Dental Surgery (Admiralty)',
						'Q & M Dental Surgery (Aljunied)',
						'Q & M Dental Surgery (Ang Mo Kio Central)',
						'Q & M Dental Surgery (Bedok)',
						'Q & M Dental Surgery (Bishan)',
						'Q & M Dental Surgery (Boon Lay)',
						'Q & M Dental Surgery (Boon Lay Mrt)',
						'Q & M Dental Surgery (Braddell)',
						'Q & M Dental Surgery (Bt. Batok)',
						'Q & M Dental Surgery (Bt. Panjang)',
						'Q & M Dental Surgery (Bt. Timah)',
						'Q & M Dental Surgery (Buangkok Mrt)',
						'Q & M Dental Surgery (Clementi Central)',
						'Q & M Dental Surgery (Clementi)',
						'Q & M Dental Surgery (Elias Mall)',
						'Q & M Dental Surgery (Eunos Mrt)',
						'Q & M Dental Surgery (Gombak)',
						'Q & M Dental Surgery (Gombak Mrt)',
						'Q & M Dental Surgery (Hougang Central)',
						'Q & M Dental Surgery (Hougang Mall)',
						'Q & M Dental Surgery (Hougang Plaza)',
						'Q & M Dental Surgery (Jelapang)',
						'Q & M Dental Surgery (Jurong East Central)',
						'Q & M Dental Surgery (Kallang Mrt)',
						'Q & M Dental Surgery (Khatib) ',
						'Q & M Dental Surgery (Marine Parade) ',
						'Q & M Dental Surgery (Marsiling)',
						'Q & M Dental Surgery (Novena)',
						'Q & M Dental Surgery (Old Airport Rd) ',
						'Q & M Dental Surgery (Pasir Ris)',
						'Q & M Dental Surgery (Punggol)',
						'Q & M Dental Surgery (Redhill MRT)',
						'Q & M Dental Surgery (Sembawang)',
						'Q & M Dental Surgery (Sembawang Mrt)',
						'Q & M Dental Surgery (Serangoon)',
						'Q & M Dental Surgery (Serangoon Central)',
						'Q & M Dental Surgery (Serangoon Garden)',
						'Q & M Dental Surgery (Serangoon North)',
						'Q & M Dental Surgery (Sims Place)',
						'Q & M Dental Surgery (Tampines)',
						'Q & M Dental Surgery (Tampines Central)',
						'Q & M Dental Surgery (Tampines Mrt)',
						'Q & M Dental Surgery (Teck Whye)',
						'Q & M Dental Surgery (Tiong Bahru)',
						'Q & M Dental Surgery (Toa Payoh)',
						'Q & M Dental Surgery (Toa Payoh Central)',
						'Q & M Dental Surgery (Toh Yi)',
						'Q & M Dental Surgery (Yishun Central)',
						'Quek & Me Dental Surgery',
						'R&C Dental(The Star) Pte. Ltd.',
						'R&C Dental(Toa Payoh) Pte. Ltd.',
						'Radiance Dental Care @ Aljunied',
						'Radiance Dental Care @ Dawson',
						'Radiance Dental Care @ Thomson',
						'Rafflesdental (Asia Square Tower)',
						'Rafflesdental (Bukit Batok Central)',
						'Rafflesdental (Marina Bay)',
						'Rafflesdental (Holland Village)',
						'Rafflesdental (Sembawang Way)',
						'Rafflesdental (Tampines)',
						'Rafflesdental (Terminal 3)',
						'Rafflesdental (Toa Payoh Central)',
						'Rafflesdental (Causeway Point)',
						'Rafflesdental (Sengkang Square)',
						'RafflesDental (Our Tampines Hub)',
						'RaffesDental (at Hillion Mall)',
						'Rafflesia Dental Surgery',
						'Raintree Dental Clinic',
						'Rapha Specialist Clinic',
						'Redhill Dental Surgery Pte Ltd',
						'Regent Dental Clinic',
						'Robertson Choo Oehlers Lee & Lye Pte Ltd',
						'Rochor Centre Dental Surgery – Veerasamy Road',
						'Rochor Centre Dental Surgery – Rochor Road',
						'Rochor Dental Clinic Pte Ltd',
						'Royce Dental Surgery (Clementi)',
						'Royce Dental Surgery (Ghim Moh)',
						'Royce Dental Surgery (Woodlands)',
						'Royce Dental Surgery (at West Point Hospital Corporation Drive)',
						'Royce Dental Surgery (Marine Parade)',
						'Royce Dental Surgery [YKB (Tampines) Pte. Ltd.] ',
						'Royce Dental Surgery [YKB (Bukit Batok) Pte. Ltd.] ',
						'S A Loh Dental Surgery Pte Ltd ',
						'Sainte Chapelle Orthodontics And Aesthetic Dentistry ',
						'Saw & Lee Dental Surgery ',
						'Segar Vale Dental Surgery Sembawang Dental Surgery',
						'Sengkang Dental Surgery ',
						'Sensational Smiles Dentistry Polygems Dental Care (Seletar) ',
						'Shang Dental (Serangoon North) ',
						'Shang Dental (Kallang) ',
						'Sharon Dental Surgery',
						'Shenton Dental Group ',
						'Shenton Dental Surgery ',
						'Shine Dental Inc ',
						'Shuang Dentistry ',
						'Simon Dental Surgery',
						' Simply Dental ',
						'Simply Endodontics Pte Ltd',
						'Singapore Dental Implant Centre',
						'Singh Implant & Dental Surgery Pte Ltd',
						'SMG Dental',
						'Smile Avenue Dentistry',
						'Smile Care Dental Surgery',
						'Smile Centre For Dental Excellence ',
						'Aesthetics, Oral Surgery And Dental Implantology ',
						'Smile Central Clinic (Hougang Central)',
						'Smile Central Clinic (Aljunied)',
						'Smile Central Clinic (Toa Payoh)',
						'Smile Central Clinic (Hougang Mall)',
						'Smile Central Clinic (at Jurong Gateway)',
						'Smile Central Dental Aljunied Pte. Ltd',
						'Smile Central Dental Toa Payoh Pte. Ltd',
						'Smile Concept Dental Practice',
						'Smile Dental @ Marine Terrace Pte Ltd',
						'Smile Dental Centre For Aesthetics Pte Ltd',
						'Smile Dental Group',
						'Smile Doctor',
						'Smile Doctor Aesthetics & Implant Dentistry',
						'Smile Doctor Dentalcare @ Punggol Waterway',
						'Smile Inc. Dental Surgeons - Marina Bay',
						'Smile Inc. Dental Surgeons – Mandarin Gallery',
						'Smile Inc. Dental Surgeons - One Raffles Place',
						'Smile Link Dental Pte. Ltd.',
						'Smile Makers Dental Clinic',
						'Smile Street Dental Clinic',
						'Smilepoint Dental Centre',
						'Smiles R Us Dental (Woodlands Mart)',
						'Smiles R Us Dental (Champions Court)',
						'Smiles R Us Dental Centre (Tanjong Katong)',
						'Smiles R Us Dental (Aljunied)',
						'Smilearts Dental Studio (Buangkok)',
						'SmileArts Dental Studio (Hillview)',
						'Smilearts Dental Studio (Marine Parade)',
						'Smilearts Dental Studio (Tiong Bahru)',
						'Smile Designers Dental Clinic ',
						'Smile Design Dental Practice',
						'Smilefocus Implant & Restorative ',
						'Smilepod Dentistry Llp Smileworks Pte Ltd ',
						'Smileworks @Keat Hong Pte Ltd ',
						'Smileworks @ Mirage Pte. Ltd. ',
						'Smiley Dentalcare',
						'Sparkle Dental Surgery Specialist Dental Group ',
						'Specialist Oral Surgeons ',
						'St Andrew’s Dental Surgeons ST Healthcare Pte Ltd ',
						'Starbite Dental Centre',
						'Star Dental Surgery Pte Ltd ',
						'Still Road Dental Surgery',
						'Straits Dental Group ',
						'Straits Dental Group Cbp',
						'Straits Dental Group (TS) Pte Ltd',
						'Sunshine Smile Dental “Smile For Life” Supreme Dental Surgery',
						'Sunshine Smile Dental Implant Centre Pte Ltd Sydney Dental Clinic',
						'Symmetry Dentofacial Aesthetics',
						'Synergy Dental Specialists',
						'T&T Dental Surgery',
						'T32 Dental Centre',
						'T32 Dental Pearl',
						'T32 Dental Pearl At Bedok Pte Ltd',
						'T32 Dental Pearl At Clementi',
						'T32 Dental Centre At Financial District',
						'Tah Chong Dental Surgery',
						'Tai Dental Surgery',
						'Tai Dental Surgery (Ang Mo Kio) Pte. Ltd.',
						'Tai Dental Surgery (City Plaza) Pte. Ltd.',
						'Tai Dental Surgery (Chai Chee) Pte. Ltd ',
						'Taman Jurong Dental Centre',
						'Tampines Dental On 81',
						'Tanglin Dental Surgeons',
						'Tanglin Dental @ Yishun',
						'Tangs Dental Group',
						'Tay Dental Surgery',
						'Tag Dental',
						'Tdh The Dental Hub (PSA Building)',
						'Tdh The Dental Hub (Yew Tee Point)',
						'Teeth @ Tiong Bahru Dental Clinic',
						'Teeth. Q Dental Surgeons @ Matilda Portico ',
						'Teehee Dental Works',
						'The Braces Practice',
						'The Dental Boutique @ Bedok Pte. Ltd',
						'The Dental Clinic',
						'The Dental Clinic And Surgery',
						'The Dental Hub @ Bedok',
						'The Dental Inn',
						'The Dental Gallery ',
						'The Dental Gallery Choa Chu Kang The Dental Gallery Dawson',
						'The Dental Pearl',
						'The Dental People Pte Ltd ',
						'',
						'The Dental Practice (Bedok) Pte Ltd',
						'The Dental Practice (Paya Lebar) Pte Ltd',
						'The Dental Practice (Pasir Ris) Pte Ltd',
						'The Dental Specialist',
						'The Dental Studio 21',
						'The Dental Lodge Sembawang',
						'The Dentist @Orchard Pte Ltd',
						'The Endodontic Office',
						'The Implant And Oral Surgery Centre',
						'The Linguandontics Clinic',
						'The Oral Care Centre',
						'The Oral Maxillofacial Practice',
						'The Oral Maxillofacial Practice (Camden Medical Centre)',
						' The Orthodontic Clinic',
						'The Smile Clinique Dental Surgeons',
						'The Smile Cliniques',
						'The Smile Division Dental Surgeons',
						'The Smile Division Dental Surgeons @ Amk Pte Ltd',
						'The Smile Division Dental Surgeons @ Tampines',
						'The Smile Division Dental Surgery',
						'The Smile Division Dental Surgery@CCK Pte Ltd',
						'The Smile Division Dental Surgery@Clementi Pte Ltd',
						'The Smile Division@Hougang Central Dental Surgery Pte Ltd ',
						'The Smile Division@Primecare Dental Clinic Pte Ltd',
						'The Smile Division@Yishun Dental Surgery Pte Ltd',
						'The Surgeons Dental Surgery',
						'The Wisdom Tooth Clinic',
						'Theng & Partners (Dental Surgeons)',
						'Thomson Dental Centre',
						'Thomson Dental Surgeons',
						'Thomson Plaza Dental Surgery',
						'Thomson Specialist Dentistry',
						'Thong Hoe Dental Surgery Pte Ltd',
						'Tiong Bahru Dental Surgery Pte Ltd',
						'Tjen Fatt Dental Surgery',
						'Tlc Dental Centre',
						'Toa Payoh Dental Centre',
						'ToofDoctor Dental Centre',
						'Toofdoctor Dental Surgeons (Adelphi)',
						'Toofdoctor Dental Surgeons (Pinnacle)',
						'Toofdoctor Dental Surgeons (Serangoon Central)',
						'Toofdoctor Dental Surgeons (Toa Payoh)',
						'Toofdoctor Dental Surgeons (Pelikat)',
						'Tooth Angel & Co. Dental Clinic',
						'Tooth Angels & Co Dental Surgeons',
						'Tooth Angels & Co Dental Surgeons (Chinatown) Pte Ltd ',
						'Tooth Art Dental Centre',
						'Tooth Matters Dental Surgery',
						'Toothcraft Dental Surgeons',
						'Toothsmith Dental Surgery',
						'Town Hall Dental Surgery (Jurong East) ',
						'Town Hall Dental Surgery (Tampines)',
						'Toronto Dental Care',
						'Tp Dental Surgeons Pte Ltd (Drs Tay & Partners) TP Dental Surgeons Tanglin',
						'Trendz Dental Surgeons Pte Ltd',
						'Tripod Dental Clinic',
						'Tripod Dental Clinic (Circuit Road)',
						'Tropical Dental Surgery',
						'True Dental Studio 22',
						'True Dental In The City Pte Ltd',
						'Twin City Endodontics Pte Ltd',
						'Twin City Medical And Dental Clinic Pte Ltd Twinkle Dental (Tampines North) Pte Ltd',
						'Twinkle Family Dentalcare Pte Ltd',
						'U Dental',
						'Ubi Dental Clinic',
						'Unity Denticare (Ang Mo Kio Hub)',
						'Unity Denticare (Bishan)',
						'Unity Denticare (Choa Chu Kang)',
						'Unity Denticare (Clementi)',
						'Unity Denticare (Golden Shoe Carpark Market Street)',
						'Unity Denticare (Hougang)',
						'Unity Denticare (Junction Nine, Yishun Ave 9)',
						'Unity Denticare (Jurong West Central 2)',
						'Unity Denticare (Orchard)',
						'Unity Denticare (Parkway Parade Marine)',
						'Unity Denticare (Rivervale Mall)',
						'Unity Denticare (Serangoon Central)',
						'Unity Denticare (Tampines)',
						'Unity Denticare (Tanjong Pagar Plaza)',
						'Unity Denticare (Toa Payoh)',
						'Unity Denticare (Yishun)',
						'Unity Denticare',
						'United Dental Surgery',
						'Universal Dental Care',
						'Universal Dental Centre',
						'Universal Dental Group',
						'Universal Dental Group (Braddell)',
						'Universal Dental Group (Woodlands)',
						'Universal Dental Surgery Pte. Ltd',
						'Universe Dental Surgery',
						'Urban Dental (Sg) Pte Ltd',
						'Urban Dental London',
						'Valley Point Dental Clinic',
						'Victoria Dentalcare (Hougang Capeview)',
						'Victoria Dentalcare (Marine Parade)',
						'Victoria Dentalcare (Marina Square)',
						'Victoria Dentalcare (Punggol Plaza)',
						'Victoria Dentalcare (Rivervale Mall)',
						'Vincent’s Dental Surgery',
						'Vista Dental Surgery (Admiralty)',
						'Vista Dental Surgery (AMK)',
						'Vista Dental Surgery (Boon Lay Mrt Station) ',
						'Vista Dental Surgery (CEX) ',
						'Vista Dental Surgery (Bukit Gombak)',
						'Vista Dental Surgery (Choa Chu Kang Drive)',
						'Vista Dental Surgery (Choa Chu Kang Mrt Station) Vista Dental Surgery (Choa Chu Kang Road) Vista Dental Surgery (Hdb Hub)',
						'Vista Dental Surgery (Hougang)',
						'Vista Dental Surgery (Sengkang)',
						'Vista Dental Surgery (Toa payoh)',
						'Vista Dental Surgery (Woodlands)',
						'V Dental',
						'Viva Dental',
						'W Dental',
						'W Eye Clinic',
						'Westfield Dental Surgery Pte. Ltd.',
						'West Coast Dental Clinic Pte Ltd',
						'West Coast Dental (Marina) Pte Ltd',
						'Wellness Dental Studio',
						'WH Dental Surgeons (Hougang)',
						'WH Dental Surgeons (Punggol)',
						'WH Dental Surgeons (The Seletar Mall)',
						'White Cloud Dental',
						'White Dental Group',
						'White & Co. Dental Care',
						'Chris Dental Surgeons',
						'Wong Dental Surgery',
						'Wong, Ong & Partners Dental Surgeons ',
						'Woodgrove Dental Surgery',
						'Woodlands Dental Clinic',
						'Wow Dental Surgery Pte Ltd',
						'WS Go Specialist Dental',
						'W. S. Go & Associates Dental Surgeons',
						'Yee Dental Surgery',
						'Yeo Dental Clinic',
						'Yio Chu Kang Dental Surgery',
						'Yip Dental Surgery Pte Ltd',
						'1728 Dental Practice (Ang Mo Kio)' ];	

               foreach($institutes as  $key => $institute) {

		            $category = InstituteCategory::inRandomOrder()->first();

		            Institute::firstOrCreate([
		            	'name' => $institute,
		            	'institute_category_id' => $response->id,
		            	'registration_no' => rand(111111,999999).$key
		            ]);
		        }
		    }    

        }




    }
}

 