export const footer_wrap: string;
export const copyrights_para: string;
export const right: string;
export const header_wrap: string;
export const container_wrap: string;
export const root: string;
export const open: string;
export const dcxGMi: string;
export const ktHroX: string;
